name: NFS Server
version: "1.0.0"
slug: nfs_server
description: Expose Home Assistant media folder via NFS.
arch: [aarch64, amd64, armv7]
privileged: [SYS_ADMIN]
apparmor: false
host_network: true
kernel_modules: true
map:
  - media:rw
ports: {}
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
  armv7: ghcr.io/home-assistant/armv7-base:latest