build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.18"
  amd64: "ghcr.io/home-assistant/amd64-base:3.18"
labels:
  org.opencontainers.image.title: "MinIO Home Assistant Add-on"
  org.opencontainers.image.description: "Docker container for MinIO.."
  org.opencontainers.image.source: "https://github.com/martemme/HomeAssistantAddons"
  org.opencontainers.image.licenses: "MIT"